# Generated by Django 4.2.1 on 2023-06-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_receipt_options_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='img_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
